package test.daogen.myibatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class TestTable {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_table.test_id
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    private Long testId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_table.test_int
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    private Integer testInt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_table.test_date
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    private Date testDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_table.test_string
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    private String testString;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_table.test_decimal
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    private BigDecimal testDecimal;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_table.test_id
     *
     * @return the value of test_table.test_id
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_table.test_id
     *
     * @param testId the value for test_table.test_id
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_table.test_int
     *
     * @return the value of test_table.test_int
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public Integer getTestInt() {
        return testInt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_table.test_int
     *
     * @param testInt the value for test_table.test_int
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public void setTestInt(Integer testInt) {
        this.testInt = testInt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_table.test_date
     *
     * @return the value of test_table.test_date
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public Date getTestDate() {
        return testDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_table.test_date
     *
     * @param testDate the value for test_table.test_date
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_table.test_string
     *
     * @return the value of test_table.test_string
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public String getTestString() {
        return testString;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_table.test_string
     *
     * @param testString the value for test_table.test_string
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public void setTestString(String testString) {
        this.testString = testString;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_table.test_decimal
     *
     * @return the value of test_table.test_decimal
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public BigDecimal getTestDecimal() {
        return testDecimal;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_table.test_decimal
     *
     * @param testDecimal the value for test_table.test_decimal
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    public void setTestDecimal(BigDecimal testDecimal) {
        this.testDecimal = testDecimal;
    }
}