package test.daogen.myibatis.dao;

import java.sql.SQLException;
import java.util.List;
import test.daogen.myibatis.model.TestTable;
import test.daogen.myibatis.model.TestTableExample;

public interface TestTableDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_table
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    void insert(TestTable record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_table
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    List selectByExample(TestTableExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_table
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    int deleteByExample(TestTableExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_table
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    int countByExample(TestTableExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_table
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    int updateByExampleSelective(TestTable record, TestTableExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_table
     *
     * @abatorgenerated Wed May 18 14:47:29 CEST 2011
     */
    int updateByExample(TestTable record, TestTableExample example) throws SQLException;
}