package test.daogen.myibatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.daogen.myibatis.model.TestTable;
import test.daogen.myibatis.model.TestTableExample;

public interface TestTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int countByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int deleteByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int deleteByPrimaryKey(Long testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int insert(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int insertSelective(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    List<TestTable> selectByExample(TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    TestTable selectByPrimaryKey(Long testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int updateByExampleSelective(@Param("record") TestTable record, @Param("example") TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int updateByExample(@Param("record") TestTable record, @Param("example") TestTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int updateByPrimaryKeySelective(TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table
     *
     * @mbggenerated Tue May 24 16:05:29 CEST 2011
     */
    int updateByPrimaryKey(TestTable record);
}